# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baidutop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='baidutop.proto',
  package='baidutop',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x62\x61idutop.proto\x12\x08\x62\x61idutop\"\xfc\x02\n\x05topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12(\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x17.baidutop.topic.Details\x1a\xab\x02\n\x07\x44\x65tails\x12/\n\theadlines\x18\x01 \x01(\x0b\x32\x1c.baidutop.topic.Details.Info\x12\x30\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x1f.baidutop.topic.Details.Context\x12,\n\x05video\x18\x03 \x01(\x0b\x32\x1d.baidutop.topic.Details.Video\x12*\n\x04info\x18\x04 \x03(\x0b\x32\x1c.baidutop.topic.Details.Info\x1a#\n\x04Info\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x1a&\n\x07\x43ontext\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x1a\x16\n\x05Video\x12\r\n\x05title\x18\x01 \x01(\tb\x06proto3'
)




_TOPIC_DETAILS_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='baidutop.topic.Details.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='baidutop.topic.Details.Info.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='baidutop.topic.Details.Info.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=345,
)

_TOPIC_DETAILS_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='baidutop.topic.Details.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='baidutop.topic.Details.Context.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='baidutop.topic.Details.Context.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=385,
)

_TOPIC_DETAILS_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='baidutop.topic.Details.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='baidutop.topic.Details.Video.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=409,
)

_TOPIC_DETAILS = _descriptor.Descriptor(
  name='Details',
  full_name='baidutop.topic.Details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headlines', full_name='baidutop.topic.Details.headlines', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='baidutop.topic.Details.context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video', full_name='baidutop.topic.Details.video', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='baidutop.topic.Details.info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TOPIC_DETAILS_INFO, _TOPIC_DETAILS_CONTEXT, _TOPIC_DETAILS_VIDEO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=409,
)

_TOPIC = _descriptor.Descriptor(
  name='topic',
  full_name='baidutop.topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='baidutop.topic.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='baidutop.topic.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='baidutop.topic.details', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TOPIC_DETAILS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=409,
)

_TOPIC_DETAILS_INFO.containing_type = _TOPIC_DETAILS
_TOPIC_DETAILS_CONTEXT.containing_type = _TOPIC_DETAILS
_TOPIC_DETAILS_VIDEO.containing_type = _TOPIC_DETAILS
_TOPIC_DETAILS.fields_by_name['headlines'].message_type = _TOPIC_DETAILS_INFO
_TOPIC_DETAILS.fields_by_name['context'].message_type = _TOPIC_DETAILS_CONTEXT
_TOPIC_DETAILS.fields_by_name['video'].message_type = _TOPIC_DETAILS_VIDEO
_TOPIC_DETAILS.fields_by_name['info'].message_type = _TOPIC_DETAILS_INFO
_TOPIC_DETAILS.containing_type = _TOPIC
_TOPIC.fields_by_name['details'].message_type = _TOPIC_DETAILS
DESCRIPTOR.message_types_by_name['topic'] = _TOPIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

topic = _reflection.GeneratedProtocolMessageType('topic', (_message.Message,), {

  'Details' : _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), {

    'Info' : _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
      'DESCRIPTOR' : _TOPIC_DETAILS_INFO,
      '__module__' : 'baidutop_pb2'
      # @@protoc_insertion_point(class_scope:baidutop.topic.Details.Info)
      })
    ,

    'Context' : _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
      'DESCRIPTOR' : _TOPIC_DETAILS_CONTEXT,
      '__module__' : 'baidutop_pb2'
      # @@protoc_insertion_point(class_scope:baidutop.topic.Details.Context)
      })
    ,

    'Video' : _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
      'DESCRIPTOR' : _TOPIC_DETAILS_VIDEO,
      '__module__' : 'baidutop_pb2'
      # @@protoc_insertion_point(class_scope:baidutop.topic.Details.Video)
      })
    ,
    'DESCRIPTOR' : _TOPIC_DETAILS,
    '__module__' : 'baidutop_pb2'
    # @@protoc_insertion_point(class_scope:baidutop.topic.Details)
    })
  ,
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'baidutop_pb2'
  # @@protoc_insertion_point(class_scope:baidutop.topic)
  })
_sym_db.RegisterMessage(topic)
_sym_db.RegisterMessage(topic.Details)
_sym_db.RegisterMessage(topic.Details.Info)
_sym_db.RegisterMessage(topic.Details.Context)
_sym_db.RegisterMessage(topic.Details.Video)


# @@protoc_insertion_point(module_scope)
